name: clang analyzer

on:
  push:
  workflow_dispatch:

jobs:
  clang_analyzer:
    name: check with clang analyzer
    runs-on: ubuntu-latest
    container:
      image: curoky/compile:ubuntu21.10
    steps:
      - uses: actions/checkout@v2

      - name: install clang analyzer
        run: |
          pip install scan-build

      - name: check version
        run: which scan-build

      - name: run clang analyzer
        run: bash script/analyzer/analyzer.sh
