name: include what you use

on:
  push:
  workflow_dispatch:

jobs:
  iwyu:
    name: check with include what you use
    runs-on: ubuntu-latest
    container:
      image: curoky/compile:ubuntu21.10
    steps:
      - uses: actions/checkout@v2

      - name: install include-what-you-use
        run: brew install -s include-what-you-use

      - name: run include-what-you-use
        run: |
          cd script/iwyu
          bash ./iwyu.sh

      - name: show iwyu out
        run: cat script/iwyu/iwyu.out

      - name: show diff
        run: git --no-pager diff
