name: unittest

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: build compiler
        run: |
          cd blink/compiler
          go get -t -v ./...
          go test -race ./...
          make

  library-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1

      - name: setup gcc
        run: sudo apt-get install -y gcc-11 g++-11 gperf

      - name: bazel sync
        run: bazel sync

      - name: bazel build
        run: bazel build //...
        env:
          CC: gcc-11
          CXX: g++-11
