name: unittest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: setup tools
        run: |
          go install github.com/mna/pigeon@latest
          go install github.com/abice/go-enum@latest

      - run: go generate ./...

      - run: go mod tidy

      - run: go build ./cmd/thrift-dump-ast

      - run: go test -race ./...
