name: unittest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: setup pigeon
        run: go install github.com/mna/pigeon@latest

      - name: setup pakcr
        run: go install github.com/gobuffalo/packr/v2/packr2@latest

      - name: build compiler
        run: |
          cd blink/compiler
          go generate
          go mod tidy
          go build -ldflags "-linkmode external -extldflags -static"
          go test -race ./...

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30

  library-cpp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1

      - name: setup gcc
        run: sudo apt-get install -y gcc-11 g++-11 gperf

      - name: bazel sync
        run: bazel sync

      - name: bazel build
        run: bazel build //...
        env:
          CC: gcc-11
          CXX: g++-11
