name: unittest

on:
  pull_request:
  push:
    branches: [master]

jobs:
  compiler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: setup pigeon
        run: go install github.com/mna/pigeon@latest

      - name: setup go-enum
        run: |
          curl -sSL -o ./go-enum https://github.com/abice/go-enum/releases/download/v0.3.9/go-enum_Linux_x86_64
          chmod +x ./go-enum
          sudo mv ./go-enum /usr/local/bin

      - name: build compiler
        run: |
          cd blink/compiler
          go generate ./...
          go mod tidy
          go build -ldflags "-linkmode external -extldflags -static"
          go test -race ./...

      - uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 30
